package com.example.finalproject;

import android.graphics.Bitmap;

/**
 * The event class has been designed to hold event information that was generated by TKT Master.com
 * @author Mike Hansen
 * @version 1.0
 * Date: 11/19/2020
 */
public class Event {
    private String name, type,url;
    private double priceMin, priceMax;
    private Bitmap promotionalImg;

    /**
     * Constructor for the Event Class. Used to populate the event more variable to come
     * @param NAME The name of the event
     * @param TYPE The type of event string format
     * @param URl the url to the ticketMaster event site
     */
    public Event(String NAME, String TYPE, String URl, String INFO){
        this.name = NAME;
        this.type = TYPE;
        this.url=URl;

    }

    // getters for all of the info
    public String getName(){return this.name;}
    public String getType(){return this.type;}
    public String getURL(){return this.url;}


    /**
     * A toString
     * @return a string with the classes variables in it
     */
    @Override
    public String toString() {
        return "Event{" +
                "name='" + name + '\'' +
                ", type='" + type + '\'' +
                ", url='" + url + '\'' +
                + '}';
    }
}
