package com.example.finalproject;

import android.graphics.Bitmap;

/**
 * The event class has been designed to hold event information that was generated by TKT Master.com
 * @author Mike Hansen
 * @version 1.0
 * Date: 11/19/2020
 */
public class Event {
    private String name, type,url;
    private double priceMin, priceMax;
    private String imgURL, saved;
    private long id;

    /**
     * Constructor for the Event Class. Used to populate the event more variable to come
     * @param NAME The name of the event
     * @param TYPE The type of event string format
     * @param URl the url to the ticketMaster event site
     * @param min the min price of a ticket
     * @param max the max price of a ticket
     * @param IMGURL the image url of the event
     */
    public Event(String NAME, String TYPE, String URl, double min, double max,long ID,String IMGURL, String SAVED){
        this.name = NAME;
        this.type = TYPE;
        this.url=URl;
        this.priceMin = min ;
        this.priceMax=max;
        this.id =ID;
        this.imgURL= IMGURL;
        this.saved = SAVED;


    }

    // getters for all of the info
    public String getName(){return this.name;}
    public String getType(){return this.type;}
    public String getURL(){return this.url;}
    public double getPriceMin(){return this.priceMin;}
    public double getPriceMax(){return this.priceMin;}
    public long getId(){return this.id;}
    public String getImgURL(){return this.imgURL;}
    public String getSaved(){return this.saved;}

    //setter
    public void setID(long dbID){
        this.id = dbID;

    }
    public void setSaved(String s){
        this.saved=s;
    }


    /**
     * A toString
     * @return a string with the classes variables in it
     */
    @Override
    public String toString() {
        return name;
    }
}
