/**
 * The event class has been designed to hold event information that was generated by TKT Master.com
 * @author Mike Hansen
 * @version 1.0
 * Date: 11/19/2020
 * */

package com.example.finalproject;

import androidx.annotation.NonNull;
import androidx.appcompat.app.ActionBarDrawerToggle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.drawerlayout.widget.DrawerLayout;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;

import com.google.android.material.navigation.NavigationView;

public class MainActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener{
    SharedPreferences prefs = null;
    Button toTicket;
    Button toRecipe;
    Button toAudio;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar myToolbar = findViewById(R.id.toolbar);
        setSupportActionBar(myToolbar);

        //For NavigationDrawer:
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(this,
                drawer, myToolbar, R.string.open, R.string.close);
        drawer.addDrawerListener(toggle);
        toggle.syncState();

        NavigationView nav = findViewById(R.id.nav_view);
        nav.setNavigationItemSelectedListener(this);

        toTicket = findViewById(R.id.toTicket);
        toRecipe = findViewById(R.id.toRecipe);
        toAudio = (Button) findViewById(R.id.toAudio);

        Intent goToTicket = new Intent(this,TicketMasterActivity.class);

        //Recipe button goes to Recipe Activity
        Intent goToRecipe = new Intent(this,RecipeActivity.class);
        toRecipe.setOnClickListener(v -> startActivity(goToRecipe));

        toTicket.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(goToTicket);
            }
        });

        Intent goToAudio = new Intent(this, AudioDatabaseActivity.class);
        toAudio.setOnClickListener(v -> startActivity(goToAudio));


        Button covbutton = findViewById(R.id.toCovid);
        covbutton.setOnClickListener( click -> {
            Intent goToCovid = new Intent(MainActivity.this, CovidData.class);
            startActivity(goToCovid);});
    }

    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        Intent goToTicket = new Intent(this,TicketMasterActivity.class);
        Intent goToRecipe = new Intent(this,RecipeActivity.class);
        Intent goToAudio = new Intent(this, AudioDatabaseActivity.class);
        Intent goToCovid = new Intent(this, CovidData.class);
        switch (item.getItemId()) {
            case R.id.backToTM:
                startActivity(goToTicket);
                break;
            case R.id.backToRecipe:
                startActivity(goToRecipe);
                break;
            case R.id.backToAudio:
                startActivity(goToAudio);
                break;
            case R.id.backToCovid:
                startActivity(goToCovid);
                break;
        }
        return true;
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu items for use in the action bar
        MenuInflater inflater = getMenuInflater();
        inflater.inflate(R.menu.toolbar_menu, menu);
        return true;
    }
}